This thesis addressed a practical problem arising in the post-processing of telemetry data from automotive test drives. In the examined workflow at Skoda Auto, engineers and technicians already have access to large amounts of measured data, yet extracting useful information from it remains unnecessarily slow and repetitive. The analytical part of the work showed that the main bottleneck is not the acquisition of the data itself, but the later processing of tabular exports, repeated comparison of measurements, and the lack of a lightweight tool tailored to everyday engineering analysis.

Based on these findings, I evaluated existing categories of software used in automotive and telemetry-oriented environments, including professional engineering platforms, OBD-II diagnostic tools, and general telemetry analysis solutions. The survey confirmed that powerful products already exist, but also showed that they do not fully match the needs of the target users in this case. Many are designed for ECU development, proprietary measurement ecosystems, or large-scale enterprise deployments. Others are easier to access, but remain focused on diagnostics rather than efficient comparative analysis of exported test-drive data. In the given context, a dedicated application represented the most suitable solution.

The design part of the thesis therefore focused on the architecture of a multiplatform desktop application capable of supporting this workflow. I chose Python because of its rapid development cycle and strong data-processing ecosystem. On the interface side, PyQt provided a mature framework for the desktop user interface. An important architectural contribution is the separation of concerns between data loading and transformation, application logic, rendering, and user interface components.

The practical result of the thesis is a working software application that goes beyond a proof of concept. The implemented solution supports loading and preprocessing ODIS-exported data, normalization of channels, handling of multiple datasets, and visualization in layouts suitable for different comparison tasks. Beyond standard plotting, the application also includes analytical functions that directly reflect the identified needs of users: descriptive statistics, delta-curve visualization, correlation-based comparison, statistical anomaly detection based on standard deviation thresholding, and an unsupervised machine-learning extension. The resulting application is therefore not only a viewer of data, but also a tool for finding suspicious behavior and useful relationships within measurements.

An important part of the work was also verifying that the application can be used in practice. For that reason, the thesis covered documentation, testing, versioning, and packaging in addition to implementation itself. The project was supported by user documentation, a reproducible development environment, automated tests for the key parts of the codebase, and a release process resulting in a standalone executable suitable for distribution in a restrictive corporate environment. Regular feedback from users influenced both the interface and the analytical features, and confirmed that practical usability is just as important as technical sophistication.
